Sprint 10
superaydumov/ImageFeed pull request #3
Opened 2023-08-11 14:21 UTC by superaydumov

Pull request according to Yandex Practikum course.

2023-08-13 11:51 UTC, protos17 requested changes

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +    func loginButtonUISetup() {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, когда они используются только внутри области объявления.

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +                fatalError("Failed to prepare for \(webSegueIdentifier)") }
Хочу отметить, что в продакшене не используется fatalError, кроме случаев, когда это необходимо, например, в банковской приложении при обнаружении джейлбрейка.

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
Обычно используем такой порядок: сначала перечисляем свойства класса, затем функции. При этом также делим на приватные и публичные блоки. А функции перечисляют в таком порядке: `init`ы, `override`ы, блоки публичных и приватных функций, и далее блок c аннотацией `@IBAction`

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +
Лишние отступы рекомендую убирать

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +fileprivate let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Рекомендую перенести в Constants

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +fileprivate let constants = Constants()
Константы лучше сделать как static let и обращаться к ним сразу через точку:

Constants.accessKey

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +    @IBOutlet weak var loginButton: UIButton!
Рекомендую указать как private

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBOutlet weak var progressView: UIProgressView!
Рекомендую указать как private

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +        let url = urlComponents.url!
Рекомендую сделать проверку, вместо принудительного извлечения

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: UIButton) {
Рекомендую указать как private

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Constants.swift
> +    let defaultbaseURL = URL (string: "https://api.unsplash.com/")!
Рекомендую указать как static let и образаться без создания экземпляра структуры

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/Models/OAuthTokenResponseBody.swift
> +        case scope = "scope"
Если CodingKey совпадает с полем, его можно не писать:

case tokenType = "token_type"
case scope

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    static let shared = OAuth2Service()
При использовании синглтона рекомендую еще добавлять:

private init() {}

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                self.authToken = authToken
Можно присвоить сразу, без введения новой константы:

self.authToken = body.accessToken

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +            baseURL: URL(string: "https://unsplash.com")!)
Реокмендую перенести в Constants

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +            else { fatalError("Failed to prepare for \(ShowAuthentificationScreenSegueIdentifier)")}
Рекомендую fatalError заменить на return

2023-08-13 11:51 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                print ("There's a problem with token!")
Рекомендую показать алерт с ошибкой пользователю

2023-08-15 09:18 UTC, superaydumov commented on ImageFeed/SplashViewController/SplashViewController.swift
> +            else { fatalError("Failed to prepare for \(ShowAuthentificationScreenSegueIdentifier)")}
при попытке заменить на return и изменить функцию для возвращения строки, сразу ругается на то, что функция не переопределяет метод из superclass

2023-08-15 09:19 UTC, superaydumov commented on ImageFeed/SplashViewController/SplashViewController.swift
> +            else { fatalError("Failed to prepare for \(ShowAuthentificationScreenSegueIdentifier)")}
<img width="838" alt="image" src="https://github.com/superaydumov/ImageFeed/assets/131291379/4a08d7fb-83f1-4e7e-8e92-2166fcb4c309">

2023-08-15 09:23 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +            else { fatalError("Failed to prepare for \(ShowAuthentificationScreenSegueIdentifier)")}
Ну правильно, не нужно сам метод менять, нужно всего лишь заменить на return:
guard ... as? AuthViewController else { return }

2023-08-15 10:08 UTC, superaydumov commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                self.authToken = authToken
Не поручилось использовать эту конструкцию. Выдает ошибку, а как её правильно решить не знаю (что поставить во второе условие nil coalescing operator).

2023-08-15 10:13 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                self.authToken = authToken
Для таких случаев рекомендую обращаться к Наставнику или Наставнице :)

2023-08-15 11:12 UTC, closed without merging